name: Deploy HCD Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm install --prefix ./hnc-vue -g
      # - run: npm install -g @vue/cli
      - run: npm install --global surge
      - run: npm --prefix ./hnc-vue run build
      - run: surge ./hnc-vue/dist/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
