name: Deploy HCD Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - run: cd hnc-vue/
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --global surge
      - run: npm --prefix ./hnc-vue run build
      - run: surge ./hnc-vue/dist/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
